"""
Report Service for generating PDF patient reports.
"""
import os
from datetime import datetime
from typing import Dict, Any, List
from io import BytesIO

from reportlab.lib.pagesizes import letter # type: ignore
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image # type: ignore
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle # type: ignore
from reportlab.lib import colors # type: ignore
from reportlab.lib.units import inch # type: ignore
from reportlab.graphics.shapes import Drawing # type: ignore
from reportlab.graphics.charts.barcharts import VerticalBarChart # type: ignore

from app.services.firestore import firestore_service


class ReportService:
    def __init__(self):
        self.width, self.height = letter
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()

    def _create_custom_styles(self):
        self.styles.add(ParagraphStyle(name='Header1', parent=self.styles['Heading1'], spaceAfter=12))
        self.styles.add(ParagraphStyle(name='Header2', parent=self.styles['Heading2'], spaceBefore=12, spaceAfter=6))
        self.styles.add(ParagraphStyle(name='NormalSmall', parent=self.styles['Normal'], fontSize=9, leading=11))

    async def generate_patient_report(self, patient_id: str, doctor_name: str, timeframe: str = "monthly") -> BytesIO:
        """
        Generates a PDF report for the patient.
        """
        # 1. Determine Date Range
        end_date = datetime.utcnow()
        if timeframe == "weekly":
            start_date = end_date.replace(day=end_date.day - 7) if end_date.day > 7 else end_date  # Simplified logic, better to use timedelta
            # proper timedelta
            from datetime import timedelta
            start_date = end_date - timedelta(days=7)
        else: # monthly default
             from datetime import timedelta
             start_date = end_date - timedelta(days=30)

        # 2. Fetch Data
        patient_data = await firestore_service.get_user_profile(patient_id)
        if not patient_data:
            raise ValueError(f"Patient {patient_id} not found")

        mood_logs = await firestore_service.get_mood_logs_by_date(patient_id, start_date, end_date)
        quiz_results = await firestore_service.get_quiz_results_by_date(patient_id, start_date, end_date)
        sos_alerts = await firestore_service.get_sos_alerts_by_date(patient_id, start_date, end_date)
        album_count = await firestore_service.get_album_entries_count(patient_id)
        suggestions = await firestore_service.get_suggestions(patient_id, limit=10) # Get recent suggestions
        behavior_notes = await firestore_service.get_behavioral_notes(patient_id, limit=10) # Get recent notes

        # 3. Create PDF
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72, leftMargin=72,
            topMargin=72, bottomMargin=18
        )

        elements = []

        # -- Title --
        elements.append(Paragraph(f"Patient Health Report - {timeframe.capitalize()}", self.styles['Title']))
        elements.append(Spacer(1, 12))
        
        # -- Patient Details --
        elements.append(Paragraph("Patient Details", self.styles['Header2']))
        p_info = [
            f"Name: {patient_data.get('name', 'N/A')}",
            f"Age: {patient_data.get('age', 'N/A')}",
            f"Report Generated By: Dr. {doctor_name}",
            f"Date Range: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}"
        ]
        for info in p_info:
            elements.append(Paragraph(info, self.styles['Normal']))
        elements.append(Spacer(1, 12))

        # -- Health Summary (Automatic Analysis) --
        elements.append(Paragraph("Overall Health Summary", self.styles['Header2']))
        summary_text = self._generate_summary_text(mood_logs, quiz_results, sos_alerts)
        elements.append(Paragraph(summary_text, self.styles['Normal']))
        elements.append(Spacer(1, 12))

        # -- Mood Summary --
        elements.append(Paragraph("Mood Summary", self.styles['Header2']))
        if mood_logs:
            # Mood Chart
            d = self._create_mood_chart(mood_logs)
            elements.append(d)
            elements.append(Spacer(1, 12))
            
            # Mood Table
            data = [["Date", "Mood", "Notes"]]
            for log in mood_logs[:10]: # Limit table rows
                data.append([
                    log.get('timestamp', datetime.now()).strftime('%Y-%m-%d %H:%M'),
                    log.get('mood_emoji', ''),
                    log.get('note', '')[:30] + '...' if len(log.get('note', '')) > 30 else log.get('note', '')
                ])
            t = Table(data, colWidths=[2*inch, 1*inch, 3.5*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ]))
            elements.append(t)
        else:
             elements.append(Paragraph("No mood logs found for this period.", self.styles['Normal']))
        elements.append(Spacer(1, 12))

        # -- Quiz Summary --
        elements.append(Paragraph("Quiz Performance", self.styles['Header2']))
        if quiz_results:
             data = [["Date", "Score", "Difficulty"]]
             for res in quiz_results[:10]:
                 data.append([
                     res.get('submitted_at', datetime.now()).strftime('%Y-%m-%d'),
                     f"{res.get('score', 0)} / {res.get('total_questions', 0)}",
                     res.get('difficulty', 'N/A')
                 ])
             t = Table(data, colWidths=[2*inch, 2*inch, 2*inch])
             t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                 ('GRID', (0, 0), (-1, -1), 1, colors.black),
             ]))
             elements.append(t)
        else:
            elements.append(Paragraph("No quizzes taken this period.", self.styles['Normal']))
        elements.append(Spacer(1, 12))
        
        # -- SOS Alerts --
        elements.append(Paragraph("SOS Alerts", self.styles['Header2']))
        if sos_alerts:
             elements.append(Paragraph(f"Total Alerts: {len(sos_alerts)}", self.styles['Normal'])) # Emphasize count
             data = [["Time", "Location"]]
             for alert in sos_alerts:
                 loc = alert.get('location', {})
                 loc_str = f"{loc.get('latitude', 0):.4f}, {loc.get('longitude', 0):.4f}" if loc else "Unknown"
                 data.append([
                     alert.get('timestamp', datetime.now()).strftime('%Y-%m-%d %H:%M'),
                     loc_str
                 ])
             t = Table(data, colWidths=[3*inch, 3*inch])
             t.setStyle(TableStyle([('GRID', (0, 0), (-1, -1), 1, colors.black)]))
             elements.append(t)
        else:
             elements.append(Paragraph("No SOS alerts triggered.", self.styles['Normal']))
        elements.append(Spacer(1, 12))

        # -- Clinical Notes --
        elements.append(Paragraph("Recent Doctor Suggestions", self.styles['Header2']))
        if suggestions:
            for sugg in suggestions:
                text = f"<b>{sugg.get('created_at', datetime.now()).strftime('%Y-%m-%d')}:</b> {sugg.get('suggestion_text', '')}"
                elements.append(Paragraph(text, self.styles['NormalSmall']))
                elements.append(Spacer(1, 4))
        else:
            elements.append(Paragraph("No recent suggestions.", self.styles['Normal']))
            
        elements.append(Paragraph("Recent Caregiver Behavioral Notes", self.styles['Header2']))
        if behavior_notes:
            for note in behavior_notes:
                text = f"<b>{note.get('created_at', datetime.now()).strftime('%Y-%m-%d')}:</b> {note.get('note_text', '')}"
                elements.append(Paragraph(text, self.styles['NormalSmall']))
                elements.append(Spacer(1, 4))
        else:
            elements.append(Paragraph("No recent behavioral notes.", self.styles['Normal']))

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer

    def _generate_summary_text(self, mood_logs, quiz_results, sos_alerts) -> str:
        summary = []
        
        # Mood analysis
        if mood_logs:
            positive_emojis = ["😊", "😄", "😃", "🙂", "🤗"]
            pos_count = sum(1 for log in mood_logs if log.get('mood_emoji') in positive_emojis)
            mood_percent = (pos_count / len(mood_logs)) * 100
            summary.append(f"Patient has been in a positive mood {mood_percent:.0f}% of the time.")
        else:
            summary.append("No mood data available.")
            
        # Quiz analysis
        if quiz_results:
            avg_score = sum(r.get('score', 0) for r in quiz_results) / len(quiz_results)
            summary.append(f"Average quiz score is {avg_score:.1f}.")
        
        # SOS
        if sos_alerts:
            summary.append(f"Warning: {len(sos_alerts)} SOS alerts were triggered in this period.")
        else:
            summary.append("No SOS alerts reported.")

        return " ".join(summary)

    def _create_mood_chart(self, mood_logs):
        # Count moods
        mood_counts = {}
        for log in mood_logs:
            emoji = log.get('mood_emoji', '?')
            mood_counts[emoji] = mood_counts.get(emoji, 0) + 1
            
        drawing = Drawing(400, 200)
        data = [tuple(mood_counts.values())]
        
        bc = VerticalBarChart()
        bc.x = 50
        bc.y = 50
        bc.height = 125
        bc.width = 300
        bc.data = data
        bc.strokeColor = colors.black
        bc.valueAxis.valueMin = 0
        bc.valueAxis.valueMax = max(mood_counts.values()) + 1 if mood_counts else 10
        bc.categoryAxis.labels.boxAnchor = 'ne'
        bc.categoryAxis.labels.dx = 8
        bc.categoryAxis.labels.dy = -2
        bc.categoryAxis.labels.angle = 30
        bc.categoryAxis.categoryNames = list(mood_counts.keys())
        
        drawing.add(bc)
        return drawing

report_service = ReportService()
